---
name: frontend
description: A new Flutter project.
publish_to: none
version: 8.0.0+8
environment:
  sdk: ">=3.0.5 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: "^1.0.2"
  flutter_svg: "^2.0.7"
  flutter_secure_storage: "^8.0.0"
  dio: "^4.0.6"
  json_annotation: "^4.8.0"
  table_calendar: "^3.0.9"
  intl: "^0.18.0"
  fluttertoast: "^8.2.2"
  firebase_core: "^2.21.0"
  firebase_messaging: "^14.5.0"
  flutter_local_notifications: "^14.0.0+1"
  url_launcher: "^6.2.1"
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: "^2.0.0"
  build_runner: "^2.3.3"
  json_serializable: "^6.6.0"
flutter:
  uses-material-design: true
  assets:
  - asset/image/
  - asset/image/tab_icon/
  fonts:
  - family: NanumSquare
    fonts:
    - asset: asset/font/nanum_square/NanumSquareOTF_acEB.otf
      weight: 900
    - asset: asset/font/nanum_square/NanumSquareOTF_acB.otf
      weight: 700
    - asset: asset/font/nanum_square/NanumSquareOTF_acR.otf
      weight: 500
    - asset: asset/font/nanum_square/NanumSquareOTF_acL.otf
      weight: 400
